#!/bin/bash

. parse-args "$@"

docker buildx build . \
  --progress=plain \
  --no-cache \
  --tag da51adea/amd64-addon-amniotic:$VERSION \
  --file /opt/dev/repo/amniotic/ha/addon/Dockerfile \
  --platform linux/amd64 \
  --pull \
  --label io.hass.version=$VERSION \
  --label io.hass.arch=amd64 \
  --label io.hass.type=addon \
  --label io.hass.name=Amniotic \
  --label io.hass.description="A multi-output ambient sound mixer for Home Assistant" \
  --label io.hass.url=https://fmtr.link/amniotic \
  --build-arg BUILD_FROM=ghcr.io/home-assistant/amd64-base:latest \
  --build-arg BUILD_VERSION=$VERSION \
  --build-arg BUILD_ARCH=amd64