#!/bin/bash
. parse-args "$@"
set -euo pipefail
set -x

BASEDIR="/tmp/esphome"
WORKDIR="$BASEDIR/work"
CONFIGDIR="$BASEDIR/config"
PLATFORMIO_DIR="$BASEDIR/platformio"

mkdir -p "$WORKDIR" "$PLATFORMIO_DIR" "$CONFIGDIR"

CMD="compile /work/config.yaml" # run /config/config.yaml --device ${NAME}.lan

docker run --rm -it --network host \
  -e HOME=/tmp \
  -e NAME -e FRIENDLY -e PASSWORD -e PASSWORD_RECOVERY \
  -v "$FILE":/work/config.yaml:ro \
  -v "$WORKDIR":/work \
  -v "$CONFIGDIR":/config \
  -v "$PLATFORMIO_DIR":/tmp/.platformio \
  --user "1000:1000" \
  ghcr.io/esphome/esphome $CMD